#!/usr/bin/env bash

source "$HOME/.config/sketchybar/variables.sh" # Loads all defined colors

# General bar and defaults

sketchybar --bar height=30 \
	color="$BAR_COLOR_2" \
	shadow="$SHADOW" \
	position=bottom \
	sticky=on \
	padding_right=0 \
	padding_left=3 \
	corner_radius="$CORNER_RADIUS" \
	y_offset=2 \
	margin=5 \
	blur_radius=20 \
	notch_width=200 \
	--default updates=when_shown \
	icon.font="$FONT:Bold:13.5" \
	icon.color="$ICON_COLOR" \
	icon.padding_left="$PADDINGS" \
	icon.padding_right="$PADDINGS" \
	label.font="$FONT:Bold:13.0" \
	label.color="$LABEL_COLOR" \
	label.padding_left="$PADDINGS" \
	label.padding_right="$PADDINGS" \
	background.padding_right="$PADDINGS" \
	background.padding_left="$PADDINGS" \
	popup.background.border_width=1 \
	popup.background.corner_radius=11 \
	popup.background.border_color="$POPUP_BORDER_COLOR" \
	popup.background.color="$POPUP_BACKGROUND_COLOR" \
	popup.background.shadow.drawing="$SHADOW"

sketchybar --add item flow left \
           --set flow update_freq=1 \
        	      script="$PLUGIN_DIR/flow.sh" \
	              click_script="sketchybar -m --set flow popup.drawing=toggle" \
	              popup.background.border_width=3 \
                      popup.background.corner_radius=4 \
                      popup.background.border_color=0xFFCA9EE6 \
		      popup.background.color=0xFF737994 \
		      popup.horizontal=on \
		      popup.align=center \
          background.corner_radius="$CORNER_RADIUS" \
          background.color="$BAR_COLOR" \
	        background.height=26 \
	        background.border_color="$CYAN" \
	        background.padding_right=5 \
          icon.padding_left=10 \
	        background.drawing=on \
        	label.padding_right=10 \
		      \
	   --add item flow.start popup.flow \
	   --set flow.start label="Start" \
	                    click_script="osascript -e 'tell application \"Flow\" to start' ; sketchybar -m --set flow popup.drawing=toggle" \
	   		    \
	   --add item flow.stop popup.flow \
	   --set flow.stop label="Stop" \
	                   click_script="osascript -e 'tell application \"Flow\" to stop' ; sketchybar -m --set flow popup.drawing=toggle" \
	   		   \
	   --add item flow.skip popup.flow \
	   --set flow.skip label="Skip" \
	                   click_script="osascript -e 'tell application \"Flow\" to skip' ; sketchybar -m --set flow popup.drawing=toggle" \
			   \
	   --add item flow.reset popup.flow \
	   --set flow.reset label="Reset" \
	                   click_script="osascript -e 'tell application \"Flow\" to reset' ; sketchybar -m --set flow popup.drawing=toggle" \
			   \
	   --add item flow.show popup.flow \
	   --set flow.show label="Show" \
	                   click_script="osascript -e 'tell application \"Flow\" to show' ; sketchybar -m --set flow popup.drawing=toggle" \

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center (of notch)
source "$ITEM_DIR/spotify.sh"
source "$ITEM_DIR/quote.sh"

# Right
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/cpu.sh"

#################### Finalizing Setup ####################

sketchybar --hotload true

sketchybar --update

echo "sketchybar configuration loaded.."
