#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_shadow float \
	window_animation_duration 0.1 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	window_opacity on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 10 \
	bottom_padding 10 \
	left_padding 10 \
	right_padding 10 \
	window_gap 8 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:0:35

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="Stats" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
yabai -m rule --add app="Pomotroid" manage=off
yabai -m rule --add app="Anki" opacity=0.90
yabai -m rule --add app="Raycast" sticky=on manage=off
yabai -m rule --add app="OpenVPN Connect" manage=off

yabai -m config --space 9 layout float

yabai -m space --rotate 90
yabai -m space --mirror y-axis
yabai -m space --mirror x-axis


echo "yabai configuration loaded.."

